import { useState, useEffect } from 'react'
import './ResultDisplay.css'

function ZoneBadge({ zone }) {
  if (!zone) return null
  const z = zone.toString().toLowerCase()
  const cls = `risk-level risk-${z === 'green' || z === 'low' ? 'low' : z === 'yellow' || z === 'medium' ? 'medium' : 'high'}`
  return <span className={cls}>{zone}</span>
}

export default function ResultDisplay({ result, loading, error }) {
  const [expanded, setExpanded] = useState({})
  const [animated, setAnimated] = useState(false)

  useEffect(() => {
    if (result) {
      setAnimated(true)
      const t = setTimeout(() => setAnimated(false), 800)
      return () => clearTimeout(t)
    }
  }, [result])

  if (!result && !loading && !error) {
    return (
      <div className="result-container empty">
        <p>Submit your analysis to see results</p>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="result-container loading">
        <div className="spinner"></div>
        <p>Analyzing...</p>
      </div>
    )
  }

  if (error) {
    return (
      <div className="result-container error">
        <h3>Error</h3>
        <p>{error}</p>
      </div>
    )
  }

  const species = result.species || []

  return (
    <div className="result-container success">
      <div className="result-header">
        <div className="summary">
          <h3 className="summary-title">Advisory — {result.river_name || 'Location'}</h3>
          <div className="summary-meta">
            <ZoneBadge zone={result.overall_zone || result.overall || ''} />
            <span className="summary-sub">Generated by FinTrack</span>
          </div>
        </div>
      </div>

      <div className={`result-content ${animated ? 'animate' : ''}`}>
        <div className="species-grid">
          {species.length === 0 && (
            <div className="no-species">No species-specific advisories available.</div>
          )}

          {species.map((s, i) => (
            <article
              className="species-card"
              key={s.name + i}
              style={{ animationDelay: `${i * 80}ms` }}
            >
              <header className="species-head">
                <div>
                  <div className="species-name">{s.name}</div>
                  <div className="species-scientific">{s.scientific_name}</div>
                </div>
                <ZoneBadge zone={s.zone || s.zone_level || 'Unknown'} />
              </header>

              <div className="species-body">
                <p className="species-advisory">{s.fishing_advisory}</p>

                <details className="species-details">
                  <summary>Details</summary>
                  <ul>
                    {s.risk_factors?.map((rf, idx) => (
                      <li key={idx}>{rf}</li>
                    ))}
                  </ul>
                  <p><strong>Recommended gear:</strong> {s.recommended_gear}</p>
                  {s.economic_note && <p className="muted">{s.economic_note}</p>}
                </details>
              </div>
            </article>
          ))}
        </div>
      </div>
    </div>
  )
}
